#!/bin/bash

if [ -z $1 ];then echo "Usage: compile_xdp TARGET" && exit 0;fi

TARGET=$1
OBJ_TARGET=`echo ${TARGET} | sed 's|\.c|\.o|g'`

# Explain clang options:
# -O2 Moderate level of optimization (Most Optimization)
# -g Generate debug information
# -c The target file to compile
# -o The compiled object name
clang -O2 -g -target bpf -c $TARGET -o $OBJ_TARGET